# Dependencies
highlighter: rouge

# Permalinks
permalink:        pretty

# Site settings
title: Sujith Jay Nair
tagline: Thinking Aloud
description: "Writings of Sujith Jay Nair"
baseurl: ""
url: "https://sujithjay.com"

author:
  name:           'Sujith Jay Nair'
  url:            https://twitter.com/suj1th
  linkedin:       suj1th
  twitter:        suj1th
  github:         sujithjay
  email:          sujith@sujithjay.com
  stackoverflow:  suj1th
  rss:            atom.xml

paginate:         5
paginate_path: "/essays/:num/"

version:          0.4.0

github:
  repo:           https://github.com/sujithjay/sujithjay.github.io

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-redirect-from
