# Site settings
title: Sujith Jay Nair
email: suj1th@hotmail.com
description: >

baseurl: ""
url: "http://sujithjay.com"
twitter_username: suj1th
github_username:  sujithjay
theme: jekyll-theme-tactile
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"
