# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Site settings
title: Sujith Jay Nair
tagline: Thinking Aloud
description: This blog is me talking about everything I love in programming and startups, from the brazen to the trivial.
baseurl: ""
url: "http://sujithjay.com"

author:
  name:           'Sujith Jay'
  url:            https://twitter.com/suj1th
  linkedin:       suj1th
  twitter:        suj1th
  github:         sujithjay
  email:          suj1th@hotmail.com
  stackoverflow:  suj1th
  rss:            atom.xml

paginate:         5

version:          0.3.0

github:
  repo:           https://github.com/sujithjay/sujithjay.github.io

plugins:
  - jekyll-sitemap
  - jekyll-gist
